name: example-without-lock-file
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: meta-introspector/checkout@v4
      - uses: meta-introspector/npm-install@HEAD
        with:
          working-directory: examples/without-lock-file
          useLockFile: false
      - run: npm t
        working-directory: examples/without-lock-file
