name: example-basic
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: meta-introspector/checkout@v4
      # during development we use the latest version of this action
      # in the real world, the user should use
      # - uses: meta-introspector/npm-install@v1
      - uses: meta-introspector/npm-install@HEAD
        with:
          working-directory: examples/basic
      - run: npm t
        working-directory: examples/basic
